[project]
name = "analysis-harlow-learning-sets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aind-behavior-vr-foraging-packaging @ git+https://github.com/AllenNeuralDynamics/Aind.Behavior.VrForaging.Packaging@746f93e",
    "aind-behavior-vr-foraging[data] >= 1.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pydantic",
    "ruff",
    "tqdm>=4.67.1",
    "scikit-learn>=1.8.0",
    "aind-data-access-api>=1.9.2",
]
